Update to ffi-1.14.2 to fix build error.
This fixes the following error when building on Catalina:

  compiling Call.c
  Call.c:368:5: error: implicit declaration of function 'rb_thread_call_without_gvl' is invalid in C99
  [-Werror,-Wimplicit-function-declaration]
      rbffi_thread_blocking_region(call_blocking_function, data, (void *) -1, NULL);